<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>GovTrace System Report</title>
    <style>
        body { font-family: Helvetica, sans-serif; font-size: 11px; color: #333; margin: 0; padding: 0; }
        .header { text-align: center; border-bottom: 2px solid #ea580c; padding-bottom: 15px; margin-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #ea580c; margin-bottom: 5px; }
        .subtitle { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 1px; }
        
        .meta-box { background: #f9f9f9; border: 1px solid #e5e5e5; padding: 12px; border-radius: 4px; margin-bottom: 25px; }
        .meta-grid { width: 100%; border-collapse: collapse; }
        .meta-grid td { padding: 4px; vertical-align: top; }
        .meta-label { font-weight: bold; color: #555; width: 100px; }
        
        .summary-box { text-align: center; padding: 15px; border: 1px solid #ea580c; border-radius: 4px; margin-bottom: 25px; background-color: #fffaf0; }
        .summary-number { font-size: 28px; font-weight: bold; color: #ea580c; }
        .summary-text { font-size: 11px; color: #666; text-transform: uppercase; margin-top: 5px; }

        table.data { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.data th, table.data td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        table.data th { background-color: #f4f4f4; color: #333; font-weight: bold; text-transform: uppercase; font-size: 10px; }
        table.data tr:nth-child(even) { background-color: #fafafa; }
        
        .badge { display: inline-block; padding: 3px 6px; border-radius: 3px; font-size: 9px; font-weight: bold; text-transform: uppercase; color: #fff; }
        .bg-critical { background-color: #dc2626; }
        .bg-security { background-color: #be185d; }
        .bg-error    { background-color: #ea580c; }
        .bg-warning  { background-color: #d97706; }
        .bg-info     { background-color: #2563eb; }
        .bg-debug    { background-color: #6b7280; }
        .bg-default  { background-color: #9ca3af; }

        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 9px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>

    <div class="header">
        <div class="logo">GovTrace</div>
        <div class="subtitle">Official System Health & Activity Report</div>
    </div>

    <div class="summary-box">
        <div class="summary-number">{{ count($logs) }}</div>
        <div class="summary-text">Total Events Recorded</div>
    </div>

    <div class="meta-box">
        <table class="meta-grid">
            <tr>
                <td class="meta-label">Generated By:</td>
                <td>{{ $user->name ?? 'System Admin' }} ({{ $user->email ?? 'N/A' }})</td>
                <td class="meta-label">Date Generated:</td>
                <td>{{ now()->format('F j, Y - H:i:s') }}</td>
            </tr>
            <tr>
                <td class="meta-label">Date Range:</td>
                <td>
                    {{ $start_date ? \Carbon\Carbon::parse($start_date)->format('M j, Y') : 'Start of record' }}
                    to 
                    {{ $end_date ? \Carbon\Carbon::parse($end_date)->format('M j, Y') : 'Present' }}
                </td>
                <td class="meta-label">Filters Applied:</td>
                <td>
                    Severity: {{ strtoupper($level ?: 'ALL') }} | 
                    Source: {{ strtoupper($source ?: 'ALL') }}
                </td>
            </tr>
        </table>
    </div>

    <table class="data">
        <thead>
            <tr>
                <th width="15%">Timestamp</th>
                <th width="12%">Level</th>
                <th width="18%">Source</th>
                <th width="40%">Message</th>
                <th width="15%">IP Address</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($logs as $log)
                <tr>
                    <td>{{ $log->created_at->format('Y-m-d H:i') }}</td>
                    <td>
                        @php
                            $badgeClass = match($log->level) {
                                'critical' => 'bg-critical',
                                'security' => 'bg-security',
                                'error'    => 'bg-error',
                                'warning'  => 'bg-warning',
                                'info'     => 'bg-info',
                                'debug'    => 'bg-debug',
                                default    => 'bg-default',
                            };
                        @endphp
                        <span class="badge {{ $badgeClass }}">{{ $log->level }}</span>
                    </td>
                    <td>{{ $log->source }}</td>
                    <td style="word-break: break-all;">{{ Str::limit($log->message, 80) }}</td>
                    <td>{{ $log->ip_address ?: 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center; padding: 20px; color: #666;">No logs found matching the selected criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by GovTrace Platform • Page <span class="page-number"></span> • AICTE E-Governance
    </div>

</body>
</html>
